from enum import Enum


class VotingMajority(str, Enum):
    ABSOLUTE_MAJORITY = "ABSOLUTE_MAJORITY"
    ABSOLUTE_STATUTORY_MAJORITY = "ABSOLUTE_STATUTORY_MAJORITY"
    MAJORITY_THREE_FIFTHS = "MAJORITY_THREE_FIFTHS"
    MAJORITY_TWO_THIRDS = "MAJORITY_TWO_THIRDS"
    SIMPLE_MAJORITY = "SIMPLE_MAJORITY"
    STATUTORY_MAJORITY = "STATUTORY_MAJORITY"
    STATUTORY_MAJORITY_THREE_FIFTHS = "STATUTORY_MAJORITY_THREE_FIFTHS"
    STATUTORY_MAJORITY_TWO_THIRDS = "STATUTORY_MAJORITY_TWO_THIRDS"

    def __str__(self) -> str:
        return str(self.value)
