name: Docker Deploy

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Restart docker-compose
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 1337
        script: |
          cd /home/projekt/by-goscz
          git pull
          docker-compose up -d --build

